### PR TITLE
#339 - Preload JSON Schema for OpenAPI v3 to avoid ProcessingException

### PR DESCRIPTION
**Pull request by tfesenko**

### CODE REVIEW

**Comment by tfesenko** [comment]
How to QA it?
1. First, update the JSON Schema schema ID  to `"id": "http://openapis.org/v3/schema.json#"` without modifying other code. Open an arbitrary v3 spec, e.g. 
```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
    
paths: {}
```
You will see a validation error on the first line:
screen shot 2017-05-30 at 7 14 48 pm

2. Now, switch to the PR branch, open the same spec - it should be OK now.

**Comment by tfesenko** [comment]
@ghillairet , can you please review and QA?

**Review by ghillairet — APPROVED** [review]
Looks good, and QA passed.

**Comment by ghillairet** [comment]
Was it because you had to change the id each time the schema is generated? Because # as id is valid.

**Comment by tfesenko** [comment]
@ghillairet wrote:
> Was it because you had to change the id each time the schema is generated? 
 
Yes, exactly. I want to use JSON Schema from gnostic without any modifications.
> Because # as id is valid.

yes, ...and we even use the `#` as `id` for the core schema.

**Pull request merged**
