### PR TITLE
#324, #312 Missing code assist contexts in callbacks

### PR DESCRIPTION
**Pull request by tfesenko**
* #324 Missing code assist contexts in callbacks
* #312 OpenAPI v3: code template for info#termsOfService should be `"termsUrl"` 

4, 5, and 6 were already fixed.  
1 . Missing objectResource template.
     - Created a new code template in templates.xml
2 . Missing operation templates for get, post, etc.
     - Fixed template contexts
3 . Missing media types list. (This is a broader problem in OAS3, since they have several property names that are supposed to be media type names. I'll open a separate issue for this.) 
     - Created a template context, but did not create actual templates for this context as it seems to be a use case for code assist, not code templates
7 . Missing response templates.
     - Fixed template contexts

## Tests
Tests for code template contexts added to resources/code-assist/code-templates/CallbacksObject.yaml

### CODE REVIEW

**Review by ghillairet — COMMENTED** [review]
I am seeing the objectResource template but I'm not seeing any templates for the operations get/post/.... Am I missing something?

screen shot 2017-09-27 at 12 26 06

**Comment by tfesenko** [comment]
@ghillairet wrote:
> I'm not seeing any templates for the operations get/post/...

Thank you for noticing it, @ghillairet !
Fixed in 	a0e6a29

**Comment by ghillairet** [comment]
@tfesenko QA passed

**Review by ghillairet — APPROVED** [review]

**Comment by ghillairet** [comment]
I opened an issue for providing content assist for media types https://github.com/RepreZen/KaiZen-OpenAPI-Editor/issues/395

**Comment by tfesenko** [comment]
@ghillairet , thank you for extracting #395!
Merging

**Pull request merged**
