### PR TITLE
Fix content assist for references under definitions.

### PR DESCRIPTION
**Pull request by ghillairet**
Content assist for references inside `definitions`  did not worked.

### CODE REVIEW

**Comment by tfesenko** [comment]
@ghillairet I have test errors in maven, master build is OK:

```
Tests in error: 
  SwaggerContentAssistProcessorTest.setUp:52 » IllegalState Workbench has not be...
  SwaggerContentAssistProcessorTest.setUp:52 » IllegalState Workbench has not be...

Tests run: 172, Failures: 0, Errors: 2, Skipped: 0
```

Can you please check if it works for you and fix them?

Also, there are several issues with the `com.reprezen.swagedit.tests/xtend-gen/` directory:
1. It's not added to .gitignore
2. I've got impression that it's not properly cleaned by maven and sometimes stale sources are used for maven build.

**Comment by ghillairet** [comment]
It was fix in previous PR today, once merged in master it will pass.

**Comment by tfesenko** [comment]
Merge master into the task branch - build passes now.

**Comment by tfesenko** [comment]
Thank you for locating and fixing this bug!

**Pull request merged**
